base_locale: es
locales: [en, eu]
ignore_unused:
  - 'activemodel.attributes.participando_authorization_handler.*'
  - 'decidim.authorization_handlers.participando_authorization_handler.*'
  - 'decidim.participando_authorization_handler.document_types.*'
